apply plugin: 'com.android.library'

android {
    compileSdkVersion setup.compileSdk

    defaultConfig {
        minSdkVersion setup.minSdk
        targetSdkVersion setup.targetSdk
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            zipAlignEnabled true
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            versionNameSuffix "-DEBUG"
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    lintOptions {
        abortOnError false
    }
    namespace 'com.johnpetitto.validator'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    // AndroidX libraries
    implementation "com.google.android.material:material:1.4.0"
    // shared lib
    implementation project(':shared')
}