apply plugin: 'com.android.library'

android {
    compileSdkVersion setup.compileSdk

    defaultConfig {
        minSdkVersion setup.minSdk
        targetSdkVersion setup.targetSdk

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            zipAlignEnabled true
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            versionNameSuffix "-DEBUG"
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    lintOptions {
        disable 'InvalidPackage'
    }
    namespace 'io.github.zwieback.familyfinance.core'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    androidTestImplementation('androidx.test.espresso:espresso-core:3.1.0', {
        exclude group: 'androidx.annotation', module: 'annotation'
    })
    // AndroidX libraries
    implementation "androidx.core:core:1.9.0"
    implementation "androidx.appcompat:appcompat:1.4.0"
    implementation "com.google.android.material:material:1.4.0"
    // java.time
    implementation "com.jakewharton.threetenabp:threetenabp:${versions.timeLib}"
    // java 8 streams
    implementation "com.annimon:stream:${versions.streamLib}"
    // icons
    implementation "com.mikepenz:iconics-core:${versions.iconicsLib}"
    implementation "com.mikepenz:iconics-views:${versions.iconicsLib}"
    testImplementation 'junit:junit:4.12'
}